name: Build and deploy Node.js app to Azure Web App - test-movieapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy: # Combined job name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          cd BackEndServer && npm install
          # npm run build --if-present
          # npm run test --if-present

      # Removed Zip artifact step - No longer needed as we deploy directly

      # Removed Upload artifact step - No longer needed

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BAD45426DCA429D88675F806F283136 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FF710FF8836414CA0918C094110B58C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15DD761FDE4D4894B36D7289DC6575ED }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "test-movieapp"
          slot-name: "Production"
          package: BackEndServer # Deploy directly from the BackEndServer folder
