name: Minimal Deploy Test

on:
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code (just for context, not strictly needed for minimal test)
        uses: actions/checkout@v4

      - name: Login to Azure (Minimal Test)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BAD45426DCA429D88675F806F283136 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FF710FF8836414CA0918C094110B58C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15DD761FDE4D4894B36D7289DC6575ED }}

      - name: Minimal Deploy Command (Just to see if login works)
        run: |
          az webapp list --resource-group <YourResourceGroupName>  # Replace with your actual Resource Group
